FROM node:18.13 as build

WORKDIR /app

COPY package*.json ./

RUN npm install --force

RUN npm install --force -g @angular/cli

COPY . .

RUN ng build --configuration=production

FROM nginx:latest

COPY --from=build app/dist/main /usr/share/nginx/html

EXPOSE 4200